export const handleError = async () => {
	return {
		message: 'Whoops!',
	};
};
